### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by itapi** [vkairy/UDPServer#1]
nice project.
i would really like to learn about the async server.
but where's the client? :)

**Comment by vkairy** [comment]
Thanks.
I hope this help you in your projects. =)
I not developed a specific client.
The server can be used along any client.
In my case I use it to listen to messages sent by a embedded client application.

**Comment by itapi** [comment]
@vkairy  you mean all i have to do is just to create a socket and connect to it?
but if i want the client to run also asynchronously? (im just bad at the asynchronous part.. i use simple socket connection with a thread...guess it's no the best way haha)

**Comment by vkairy** [comment]
@itapi sorry for the delay to answer you.
Here is a link with some sample codes which I hope help you: https://gist.github.com/leandrosilva/656054
